package com.merlin.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.merlin.database.FileDB;

import com.merlin.database.FileDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileDBDaoConfig;

    private final FileDBDao fileDBDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileDBDaoConfig = daoConfigMap.get(FileDBDao.class).clone();
        fileDBDaoConfig.initIdentityScope(type);

        fileDBDao = new FileDBDao(fileDBDaoConfig, this);

        registerDao(FileDB.class, fileDBDao);
    }
    
    public void clear() {
        fileDBDaoConfig.clearIdentityScope();
    }

    public FileDBDao getFileDBDao() {
        return fileDBDao;
    }

}
